#!/usr/bin/env python

'''
This Ground Station Control will handle all messages to be sent to the Quadcopter
More deets on the way blah blah

################################################
'''

import sys
from PyQt4 import QtGui,QtCore

print "############################################################"
print "#    This is GUIllermo : The quadcopter's ground station   #"        
print "#                     Version 0.0.1                        #"
print "############################################################"


def msg():
        print 'Sent'

class Widget(QtGui.QWidget):
    #Function that initializes ground station
    def __init__(window):
        super(Widget, window).__init__()
        window.initUI()
        
    #Function that "draws" command window and most of the knick knacks
    #to be viewed in the GUI    
    def initUI(window):
        window.col = QtGui.QColor(160,160,160)
        window.square = QtGui.QFrame(window)
        window.square.setGeometry(146,46,81,29)
        window.square.setStyleSheet("QWidget { background-color: %s}" %
                                           window.col.name())

        #Connection Button
        connect_button = QtGui.QPushButton("Connect", window)
        connect_button.move(150,50)
        connect_button.clicked.connect(msg)
        
        window.setGeometry(0, 40, 2000, 950)
        window.setWindowTitle('QuadCopter Ground Station Ver. 0.0.1')
        window.setWindowIcon(QtGui.QIcon('qd_icon.png'))        
        window.show()
  
    #Function that handles close event, in case of hitting wrong button
    def closeEvent(window, event):
        reply = QtGui.QMessageBox.question(window, 'Wait up buddy!',
            "Are you sure to quit?", QtGui.QMessageBox.Yes | 
            QtGui.QMessageBox.No, QtGui.QMessageBox.No)
        if reply == QtGui.QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

    def msg():
        print 'Sent'
        window.square.setStyleSheet("QWidget { background-color: rgb(102,0,255)}")
        
    
        






            
def main():
    
    app = QtGui.QApplication(sys.argv)
    ex = Widget()
    sys.exit(app.exec_())


if __name__ == '__main__':
    main()    


